name: Build
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies and build
        run: corepack yarn install --immutable
      - name: Run tests
        run: |
          # See: https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
          echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
          corepack yarn test
      - name: Upload compiled code as artifact
        uses: actions/upload-artifact@v7
        with:
          name: ghost-cursor
          path: lib/
