name: Publish to NPM
on:
  create:
    tags:
      - v* # only run if new tag is created
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies and build
        run: yarn
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          check-version: true # only publish if the version in package.json has changed